### PR TITLE
rebase of "Normalize String.join"

### PR DESCRIPTION
**Pull request by nicu-chiciuc**
Rebased https://github.com/darklang/dark/pull/4756 and fixed string.test

a single test case was impacted (join followed by base64Encode_v0)

### CODE REVIEW

**Review by pbiggar — COMMENTED** [review]
Looks great!

**Comment by pbiggar** [comment]
Looks like unrelated changes got pulled in and got caught in a merge conflict. Apologies - would you be able to rebase again?

**Comment by pbiggar** [comment]
This is ready to merge right? It's marked as a draft so I wasn't sure. It needs to be marked "Ready to review" before github will let me merge it.

**Comment by nicu-chiciuc** [comment]
it's ready

**Pull request merged**
