### PR TITLE
Remove some externals and use rescript-webapi instead

### PR DESCRIPTION
**Pull request by OceanOak**
This replaces most Native externals with their rescript-webapi equivalents.

### CODE REVIEW

**Comment by OceanOak** [comment]
I wasn't sure if I should use reload or reloadWithForce to replace reload.

**Native**
`@val @scope(("window", "location")) external reload: bool => unit = "reload"`

**Rescript-webapi**
```
@send external reload: t => unit = "reload"
@send external reloadWithForce: (t, @as(json`true`) _) => unit = "reload"
```

**Comment by pbiggar** [comment]
> I wasn't sure if I should use reload or reloadWithForce to replace reload.
> 
> **Native** `@val @scope(("window", "location")) external reload: bool => unit = "reload"`
> 
> **Rescript-webapi**
> 
> ```
> @send external reload: t => unit = "reload"
> @send external reloadWithForce: (t, @as(json`true`) _) => unit = "reload"
> ```

Based on https://developer.mozilla.org/en-US/docs/Web/API/Location/reload, it looks like that's a non-standard parameter that only works in Firefox, so let's not use the force version.


> Also, couldn't find an equivalent for `clipboard-copy`; did I miss it, or is it under a different name?

Looks like this calls the clipboard-copy package directly. So I guess it's fine where it is (nothing to remove here)

**Comment by pbiggar** [comment]
Can you edit the description to add a changelog entry? ("Internal improvements").

I've merged, but I realize I forgot to ask about testing. Did you check that everything still works in the area these changes were made? Our integration tests are not sufficient to catch bugs here unforunately.

**Comment by OceanOak** [comment]
>Based on https://developer.mozilla.org/en-US/docs/Web/API/Location/reload, it looks like that's a non-standard parameter that only works in Firefox, so let's not use the force version.

So, I should make a new PR and replace reloadWithForce by reload right?

> I've merged, but I realize I forgot to ask about testing. Did you check that everything still works in the area these changes were made? Our integration tests are not sufficient to catch bugs here unforunately.

I have checked the autocomplete and commands as well as the redirect. If you can please point me to what I should check, that would be appreciated. I'm still not familiar enough with this to know exactly what I should look for.

**Comment by pbiggar** [comment]
> > Based on https://developer.mozilla.org/en-US/docs/Web/API/Location/reload, it looks like that's a non-standard parameter that only works in Firefox, so let's not use the force version.
> 
> So, I should make a new PR and replace reloadWithForce by reload right?

Yes please!

> > I've merged, but I realize I forgot to ask about testing. Did you check that everything still works in the area these changes were made? Our integration tests are not sufficient to catch bugs here unforunately.
> 
> I have checked the autocomplete and commands as well as the redirect. If you can please point me to what I should check, that would be appreciated. I'm still not familiar enough with this to know exactly what I should look for.

Sure, the main this is seeing if any of the functionality below causes an error in the browser console:

- the "copy" button on live values
- the live values and anything around code still lines up properly
- commands using `Alt-x` display and work properly

**Comment by OceanOak** [comment]
> Sure, the main this is seeing if any of the functionality below causes an error in the browser console:
> 
> * the "copy" button on live values
> * the live values and anything around code still lines up properly
> * commands using `Alt-x` display and work properly

All these seem to be working properly.

**Comment by pbiggar** [comment]
Great, thanks!

**Pull request merged**
