### PR TITLE
Fix flaky perm tests

### PR DESCRIPTION
**Pull request by pbiggar**

### CODE REVIEW

**Comment by StachuDotNet** [comment]
will resolve https://github.com/darklang/dark/issues/3557

**Comment by pbiggar** [comment]
Why? Is this the only thing left?

**Comment by StachuDotNet** [comment]
I suppose not - yesterday you mentinoed having a stashed PR that resolves the rest of the FSTODOs - I assumed this was it, must have been wrong.

**Comment by pbiggar** [comment]
My stashed PR removes the rest of the `FSHARPONLY`s, no `FSTODO`!

**Comment by StachuDotNet** [comment]
Aha, okay!

**Comment by pbiggar** [comment]
Redo some tests to do their own setup instead of relying on the test harness.

Also removes remaining FSHARPONLY annotations.

**Comment by pbiggar** [comment]
Note this does not actually solve the flaky tests, but merging as it's a minor step forward.

**Pull request merged**
