### PR TITLE
Start adding an OpenAI package

### PR DESCRIPTION
**Pull request by OceanOak**
Changelog:

```
Packages
- Add an OpenAI package
```

### CODE REVIEW

**Comment by OceanOak** [comment]
Would it be beneficial to include functions that support parameters beyond "prompt", such as model, tokens, temperature, etc.?

**Comment by StachuDotNet** [comment]
> Would it be beneficial to include functions that support parameters beyond "prompt", such as model, tokens, temperature, etc.?
I think it'd be useful to have an `options` object passed in, and have a `default` constant/function available.
So,
- the CompletionOptions object would house all possible options, 
- a `default` value would contain the ..default values
- and a consumer could either create a whole CompletionOptions value from scratch, or use the `{ default with ...}` syntax to override specific properties

Can wait for a separate PR, though

**Comment by StachuDotNet** [comment]
I would rename agent.dark to openai.dark - an agent logic/package wrapping this is probably worth extraction, applicable to not only this LLM but also others

**Comment by StachuDotNet** [comment]
Great!

**Pull request merged**
