### PR TITLE
Implement Int::parse in favor of String::toInt

### LINKED ISSUE #4168: Rename `String::toInt` as `Int::parse`

### LINKED ISSUE #4170: Investigate + resolve String::toInt_v2 flakiness
per #4169

### LINKED ISSUE #4196: Int::parse should use a result or an option

### PR DESCRIPTION
**Pull request by StachuDotNet**
Replaces #4188, of which I absolutely botched the Git history.

Will resolve #4168 and resolve #4170 and resolve #4196.

### CODE REVIEW

**Comment by StachuDotNet** [comment]
From last review:

> Can you add some tests with whitespace around the number? (front, back, between - and the number).
> What happens with + in the number, can we test that too?
> Maybe a test for other representations that might be accidentally parsed without our knowledge, to confirm they aren't supported (0x, 0b, 5E-5)?
> What about a number in octal format (078)?

These are done.

**Review by pbiggar — APPROVED** [review]
Wonderful!

If you had a moment, would be great to add these (great!) new tests to the old version too. I don't want to expand the scope so feel free not to, but I would like us to get into the habit of doing that going forward.

**Comment by StachuDotNet** [comment]
Resolves #4196 shortly (fixing now)

**Comment by StachuDotNet** [comment]
Ah - also, need to use the v1 error message from String::toInt, not the v0 error message. (v1 is better). One moment.

**Review by pbiggar — APPROVED** [review]

**Pull request merged**
