### PR TITLE
Put cursor in DB creation #2471

### LINKED ISSUE #2471: Put cursor in DB name on creation
When creating a DB from the sidebar, put the cursor into the DB name and allow the user to type to rename

### PR DESCRIPTION
**Pull request by ggajos**
This PR might resolve #2471

### CODE REVIEW

**Comment by pbiggar** [comment]
Code looks good. There's an integration test failing, I think as a result of this.

**Comment by ggajos** [comment]
@pbiggar Any idea what could be potential fix here? Or how to narrow down the error?

**Comment by pbiggar** [comment]
@ggajos So from the CircleCI page we can see the error is in the `rename_db_fields` integration test. That's defined in integration-tests/tests.js, and the success criteria is in client/src/app/IntegrationTests.ml. You can download the video of it running from CircleCI (check the artifacts tab), or run the test yourself - using `./scripts/run-in-docker integration-tests/run.sh --pattern=rename_db_fields`. Then you can watch the video in `rundir/videos/rename_Db_fields.mp4`.

**Comment by ggajos** [comment]
outdated

**Pull request closed without merging**
