### PR TITLE
Solving the issue with the terraform installation on arm64

### PR DESCRIPTION
**Pull request by ditansu**
Changelog:
```
Area of change
- Dockerfile 
```
## What is the problem/goal being addressed?
issue #4746  
Unable to locate package terraform on arm64 (MacBook M1 Pro) 

## What is the solution to this problem?
Changing the Terraform install way on the binary download 

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
A development experience improves on MacBook.

## How are you sure this works/how was this tested?
Run `scripts/builder --compile --test` and check that all tests passed successfuly

## What is the reversion plan if this fails after shipping?
Use previous version of Dockerfile

## Has this information been included in the comments?
Nope

### CODE REVIEW

**Comment by ditansu** [comment]
@pbiggar Hey! I can't realize why my change doesn't pass some backend test cases. What I do wrong?

**Comment by pbiggar** [comment]
> @pbiggar Hey! I can't realize why my change doesn't pass some backend test cases. What I do wrong?

That's a flaky test, so seems fine.

Can you make the PR on the light repo instead? This one is going to be archived.

**Comment by ditansu** [comment]
sure, I do

**Comment by StachuDotNet** [comment]
Closing this - the PR has been replicated in the `light` repo

**Pull request closed without merging**
