### PR TITLE
Added auto complete in lists with comma

### PR DESCRIPTION
**Pull request by actuallymab**
👋  First PR.

A fix for #2517 

I am not sure if pattern match order is perfect. Feel free to comment.

### CODE REVIEW

**Comment by pbiggar** [comment]
Will look at the pattern ordering. Can you add a test?

**Comment by pbiggar** [comment]
Thanks for this, looks great. Can you apply this approach to the existing code instead of adding new patterns? Existing code is:

```
    | InsertText ",", L (TListOpen (id, _), _), _ when onEdge ->
        let bID = gid () in
        let newExpr = E.EBlank bID (* new separators *) in
        astInfo
        |> ASTInfo.setAST (insertInList ~index:0 id ~newExpr astInfo.ast)
        |> moveToCaretTarget {astRef = ARBlank bID; offset = 0}
    | InsertText ",", L (TListComma (id, index), _), _
    | InsertText ",", _, R (TListComma (id, index), _)
      when onEdge ->
        let bID = gid () in
        let newExpr = E.EBlank bID (* new separators *) in
        astInfo
        |> ASTInfo.setAST
             (insertInList ~index:(index + 1) id ~newExpr astInfo.ast)
        |> moveToCaretTarget {astRef = ARBlank bID; offset = 0}
    | InsertText ",", _, R (TListClose (id, _), _) when onEdge ->
        let bID = gid () in
        let newExpr = E.EBlank bID (* new separators *) in
        astInfo
        |> ASTInfo.setAST (insertAtListEnd id ~newExpr astInfo.ast)
        |> moveToCaretTarget {astRef = ARBlank bID; offset = 0
```

I'd love to have tests for this case that covers this at open, close, and for a comma that isn't on open or close.

Thanks again!

**Comment by actuallymab** [comment]
@pbiggar updated existing patterns, and added two simple tests.

**Comment by pbiggar** [comment]
This failed the format checks. You can run the formatter with `scripts/format format backend`

**Comment by pbiggar** [comment]
Looks good otherwise!

**Comment by actuallymab** [comment]
Sorry, my bad 😅 should be good now 👍

**Comment by pbiggar** [comment]
Wonderful!

**Pull request merged**
