### PR TITLE
Add String::replaceAll to sql compiler

### LINKED ISSUE #2691: Add String::replaceAll support to the query compiler
The query compiler should be able to handle String::replaceAll. Part of #2424

### PR DESCRIPTION
**Pull request by cooleydw494**
Done as part of initiative to expand query compiler. #2424 
I've added String::replaceAll to the lambda_to_sql function, mapping to the postgres function "replace", and wrote a test to verify it works
This will allow the Db::query family of functions to compile the aforementioned String::replaceAll function successfully when applied to DB record values.

I think likely there should be another function to contain the logic of functions with 3 arguments (like unary and binop functions) but for now I just really want the functionality. We've also discussed evolving where the logic for each function is stored, but I'm still just focusing on expanding support within the existing infrastructure (what I'm capable of right now).

Closes #2691

### CODE REVIEW

**Comment by cooleydw494** [comment]
Btw, sorry for the extra commits that aren't relevant to the task at hand. I keep forgetting to format and check for changes to merge in before I commit

**Comment by pbiggar** [comment]
Looks great!

Could you add:
- a test where it doesn't replace anything (eg search for "xxx")
- a test where it replaces more than once

Should be good to go with those!

**Comment by cooleydw494** [comment]
> Looks great!
> 
> Could you add:
> 
> * a test where it doesn't replace anything (eg search for "xxx")
> * a test where it replaces more than once
> 
> Should be good to go with those!

done!

**Comment by cooleydw494** [comment]
hmmm, I can't see details on the integration tests and they are passing locally. Let me know what I can do. No rush, likely a tomorrow thing for me.

**Pull request merged**
