### PR TITLE
Add support to Visual Studio Codespaces

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
**Problem:**
My machine is quite old and unable to compile darklang without spinning all fans like crazy for 40 minutes and crashing after that.
**Documentation:**
- [Codespaces](https://code.visualstudio.com/docs/remote/codespaces)
- Not sure where to put docs on how to use this for other devs. Readme?
**Solution:**
Using the power of virtualization we can get any kind of machine. With the latest additions to VSCode and Visual studio, the setup to be productive in a remote environment is minimal. 
With this setup
```
scripts/builder --compile --watch --test
```
Can be run in either:
- A docker container which removes the need to have python3 and fswatch on the host machine.
- For my case in codespace - it will use the same config.

**Limitations:**
- It's required to clone the GitHub repo using **https** not via ssh. As far as I understand the reason is that for now codespaces don't yet support proxying of ssh keys into the codespace.
- To be investigated how does it work with dnsmasq - this is only initial setup. Will be doing more PR's which will add port forwarding and etc.

- [N/A ] Trello link included
- [x ] Discussed goals, problem and solution
- [ x] Information from this description is also in comments
  - [ ] No useful information
- [ ] Before/after screenshots are included
  - [x ] Screenshots aren't useful
- [ ] Intended followups are trelloed
  - [ ] No followups
- [ ] Reversion plan exists
  - [ ] Standard git revert is fine
- [ ] Tests are included (required for regressions)
  - [ ] The type system will catch it
- [ ] Specs (docs/trello) are linked in code 
  - [x ] No spec exists

### CODE REVIEW

**Comment by Maxim-Filimonov** [comment]
This is probably obsolete due to MS switch to github codespaces which has different configuration.

**Comment by pbiggar** [comment]
Thanks for looking at this! Since you first looked, I started using VSCode remote containers and so fixed a few things that I think would simplify this too.

**Comment by Maxim-Filimonov** [comment]
@pbiggar ah nice as this repo is now public GitHub code spaces should be free to use here.

**Comment by pbiggar** [comment]
Cool. If you or anyone else tries it out, would love to know how it goes or if we could improve it!

**Comment by Maxim-Filimonov** [comment]
I just tried to create code space but it didn't work.
The [image](https://github.com/darklang/dark/blob/4b80a28e28a5ef4d5ec0fb41e53aca9e372e8f35/.devcontainer/devcontainer.json#L8) being used doesn't seem to be valid image on docker hub.

Does this needs to change to dark-base/

**Comment by pbiggar** [comment]
This is the docker project: https://hub.docker.com/repository/docker/darklang/dark-rust. So I guess it needs to be darklang/dark-rust?

**Comment by Maxim-Filimonov** [comment]
Yes, I believe that would work.

**Comment by pbiggar** [comment]
Thanks @Maxim-Filimonov, I'll make the change and follow up.

**Pull request closed without merging**
