### PR TITLE
Include TAny case in client DType.decodeOld fn

### PR DESCRIPTION
**Pull request by StachuDotNet**

### CODE REVIEW

**Comment by StachuDotNet** [comment]
I'm not sure if we need this or not - untested.

**Comment by StachuDotNet** [comment]
I can't imagine this doing anything bad; I'll just merge it.

**Comment by StachuDotNet** [comment]
Got the bug locally for Tany - hope you don't mind the :cowboy_hat_face: deploy

**Comment by pbiggar** [comment]
Thanks!

**Pull request merged**
