### PR TITLE
Better CI locking

### PR DESCRIPTION
**Pull request by pbiggar**
As detailed in https://github.com/darklang/dark/issues/4066, I'm afraid things will go badly if I press "merge" on many PRs at once. This addresses that by ensuring deploys go out in the order they were merged, and will wait for other jobs to go out if they're not next.

The details have all been added in the README - let me know if anything is unclear.

### CODE REVIEW

**Comment by pbiggar** [comment]
- [ ] test before merging this

**Comment by pbiggar** [comment]
With `deploy-lock-one-remove`, the intent was to have prefixes: `deploy-lock-all-X` and `deploy-lock-one-X`, where the `one-` suffix implied it affected one build. But it's not a super great name: `remove-one` is much clearer than `one-remove`.

Any thoughts on better names?

**Comment by StachuDotNet** [comment]
I think it's fine as-is; just add a #comment right before their definitions with that explanation?

**Comment by pbiggar** [comment]
Good idea.

**Pull request merged**
