### PR TITLE
WIP: adding minimal spawndev.blazor js usage for background processing of events in wasm runtime

### PR DESCRIPTION
**Pull request by StachuDotNet**
Changelog:

```
Area of change
- details
```

Importing NuGet packages didn't work out of the box.
So, copied the whole project into ours, and trimming it down until it works. This rips out much of the repo.

Ideally, I think we contrib to spawndev, but push towards breaking it down a bit and making it a bit more stable.

At this point, most of what's here is useless to us. The relevant pieces are:
- SpawnDev.BlazorJS/SpawnDev.BlazorJS.Test/Client/Program.cs (basically "DarkEditor.fs")
- SpawnDev.BlazorJS/SpawnDev.BlazorJS.Test/App.razor ("editor-bootstrap.js" -ish)
- the SpawnDev.BlazorJS and SpawnDev.BlazorJS.WebWorkers projects which support these
  - especially: the files in the wwwroot of each, which load blazor in a background thread like our previous "BlazorWorker"
- some other bits around setting up the webworker that I'm still unfamiliar with

### CODE REVIEW

**Comment by pbiggar** [comment]
I'm sure I don't need to say this, but please don't merge without purging the history

**Comment by StachuDotNet** [comment]
lol, I wouldn't dream of it

**Comment by StachuDotNet** [comment]
whoops, messed up history. that's OK, can resolve tomorrow.

**Comment by StachuDotNet** [comment]
#4902 supersedes this (and still isn't complete)

**Pull request closed without merging**
