### PR TITLE
Add tests around `emit` StdLib fn

### PR DESCRIPTION
**Pull request by StachuDotNet**
## What is the problem/goal being addressed?
`emit_v0` and `emit_v1` are untested.

## What is the solution to this problem?
Add a `events.tests` file with tests - and generally allow for testing of `emit` within testfiles.

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
- in `EventQueue.fs`, add fn `testingGetQueue` for test purposes, to fetch all events on a queue
- add a Test-only lib fn `getQueue` that uses `testingGetQueue`
- adjust `LibExecution.Test.fs`
  - to allow for the parsing of `[test.name] with Worker MyWorker` tests
  - to add the handlers to test programs when relevant, using `Canvas.addOps` (if there's a better way to do this, please let me know)
- update the relevant README.md
- add tests around `emit`

### CODE REVIEW

**Comment by StachuDotNet** [comment]
Took a while, but this was a fun one

**Comment by StachuDotNet** [comment]
I still need to figure out why these fail for ocaml

**Review by pbiggar — COMMENTED** [review]
Looks good!

To support OCaml, you'd need to add `Test.getQueue` to OCaml's libtest. I'm fine if you don't add this though - let me know which way you want to go.

**Comment by StachuDotNet** [comment]
I took it as a personal challenge to get it working for OCaml - took me _way_ too long to figure out why the new fn wasn't exposed in `event_queue` (because I didn't add it to .mli file).

**Review by pbiggar — CHANGES_REQUESTED** [review]
Looks good! One tiny change and we can merge.

**Pull request merged**
