### PR TITLE
Change working directory when calling gsutil

### PR DESCRIPTION
**Pull request by StachuDotNet**

### CODE REVIEW

**Comment by StachuDotNet** [comment]
a separate todo: don't decode; get this info from original source and map when we need it
(we should be able to kill the decode fn)

**Review by pbiggar — APPROVED** [review]

**Comment by StachuDotNet** [comment]
Did you mean to merge this?

**Comment by pbiggar** [comment]
Yeah, sorry. Was it not ready? I can stop the deploy.

**Comment by pbiggar** [comment]
Oh, I hit close!

**Comment by pbiggar** [comment]
Whoops, thanks!

**Comment by StachuDotNet** [comment]
Thanks!

**Pull request merged**
