### PR TITLE
MPlistCons preview & analysis tests

### PR DESCRIPTION
**Pull request by ditansu**
No changelog.

Follow-up to #4840

### CODE REVIEW

**Comment by ditansu** [comment]
@StachuDotNet I've added a test to `testMatchPreview` what else need to add here? Could you please clarify what did you mean under `analysis` tests?

**Comment by StachuDotNet** [comment]
This is about what I meant!

In addition to adding the `match` _case_, though, we'll need to add actual tests against it, seeing what branches have been evaluated in the execution path, what branches have been simply previewed, etc.

If you scroll down in that file to `"test match evaluation"`, that's what I think we still need to add for the new _case_ you added

**Comment by ditansu** [comment]
@StachuDotNet I'm not sure that I understand how to organize such test. We don't have the corresponded `EType` for `MPListCons`.  Below maximum that I can do. Do you have any ideas? 
```fsharp  
t
        "list destructuring"
        (eList ([(eInt 1); (eInt 2)]))
        [ (pLClistId, "matching pat", ner (DList [DInt 1L; DInt 2L]))
          //(pListCons2, "matching rhs", ner (DList [DInt 2L; DInt 4L]))
         ]
```

**Comment by ditansu** [comment]
@StachuDotNet needs your help, please hint me here (see previous message)

**Comment by StachuDotNet** [comment]
Hi there @ditansu - I wasn't sure how to answer your questions here well. It's a bit tricky, and may not be worth further work there right now. For some of these tests, I'm really unsure what they should be, especially without the UI where I can 'play' with the preview feature.

That said, I pulled your code, edited it a bit, and recorded some thoughts. I hope this is somewhat useful - not sure where to go from here, but maybe it'll spark some ideas.

Again, this isn't super high priority but wanted to give you some feedback. Feel free to drop this PR entirely!

https://youtu.be/mXby37HmNkQ I've just uploaded this but YouTube may take some time to process it to a point where it's actually viewable. Check back in a few hours :)

**Comment by ditansu** [comment]
Hi @StachuDotNet, your explanations were incredibly detailed. I truly value the time you spent providing such insights. Thanks a lot! Not sure that I've caught all your thoughts, probably I need time to realize it. I guess we can drop this PR. Next time when I touch this part of the code, I will try to rethink it. Thanks again.

**Comment by StachuDotNet** [comment]
No worries! it was good to get the response out of my head, but yeah it's probably not worth pursuing - there are more important TODOs :)

**Pull request closed without merging**
