### PR TITLE
Simplify CDN push in CI: iter by mimetypes, not dirs

### PR DESCRIPTION
**Pull request by StachuDotNet**
per recommendation yesterday

### CODE REVIEW

**Comment by pbiggar** [comment]
What level of reading would you like here? Should I inspect deeply or just glance at it?

**Comment by StachuDotNet** [comment]
just glance is fine.
I've tested locally (proves that it works) and this is per your recommendation (so unlikely to be opposed).

**Comment by StachuDotNet** [comment]
In case the intention doesn't ring a bell, the change here is that we used to iterate over the folders in our temp directory when uploading via gsutil, and decoded the foldername (with the hacky #slash# thing) along the way. Now, we don't ever decode - we killed that fn, and instead iterate over the found mimetypes, encoding to find the 'correct' dir instead of iterating over them.

**Comment by pbiggar** [comment]
Yeah, it looked grand. Just wanted to be sure you weren't relying on a deep review for certainty before I rubber stamp it.

**Pull request merged**
