### PR TITLE
Add List::interpose to the stdlib

### PR DESCRIPTION
**Pull request by PosaLusa24**
## What is the problem/goal being addressed?
Issue #2466: Standard library lacks a list interpose/join function.

## What is the solution to this problem?
To add List::interpose to the stdlib, along with the required tests.

## How are you sure this works/how was this tested?
List::interpose tests completed successfully.

### CODE REVIEW

**Comment by pbiggar** [comment]
This looks great, thank you! I'm going to take a quick glance to see about the parameter ordering here, and I'll get back to you again shortly.

**Comment by pbiggar** [comment]
Can you make the list the first argument? That way we can pipe to it.

Thanks!

**Comment by PosaLusa24** [comment]
Sure! That'd be much better.

**Comment by pbiggar** [comment]
Amazing, thanks so much!

**Pull request merged**
