### PR TITLE
Make tab through all editable fields in body

### PR DESCRIPTION
**Pull request by br1anchen**
## What is the problem/goal being addressed?
Fixes #2615 

## What is the solution to this problem?
find editable fields in body to loop through

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
*Please include before/after screenshots/gifs if appropriate*
tab-through-2020-06-28-215001

## How are you sure this works/how was this tested?
Manually tested and integration does not fail

### CODE REVIEW

**Comment by pbiggar** [comment]
This works great for code, nice!

However, it brings a lot of jankiness to editing non-code (DBs, handler headings). For example:



The first tab doesn't move into the next blankOr, it instead moves to selecting mode (a mode which I want to get rid of, but haven't done yet).

The second tab goes into the next blankOr, however it also replaces the text with the previous text, instead of keeping the same text. This is a weird piece of code: the text is stored in `m.complete.value` and it's stateful - it needs to be updated (with an `ACSetQuery`) call as the tabs move around.

I also see some jank in HTTP headers, and moving between HTTP headers and code bodies. Most of those bugs were there before, but I'm also seeing the cursor focus on the wrong place. Can you test that out - I'd be happy to merge this once it's strictly better than the current code, even if it doesn't solve all problems.

**Comment by br1anchen** [comment]
Thanks for testing it out. Good to know other cases to test with. Will try to fix in these scenarios you mentioned.

**Comment by pbiggar** [comment]
> Thanks for testing it out. Good to know other cases to test with. Will try to fix in these scenarios you mentioned.

Thanks! 😊

**Comment by pbiggar** [comment]
We're getting rid of the client so closing this.

**Pull request closed without merging**
