### PR TITLE
Use published Blazor builds, tidy wasm.fs

### PR DESCRIPTION
**Pull request by StachuDotNet**
Since CI was yielding results inconsistent with my other PR, I'm using this PR to make very small changes one by one, seeing how CI responds, to find the cause of the issue I was facing.

### CODE REVIEW

**Comment by StachuDotNet** [comment]
- [ ] integrations tests are flaky because we're waiting for the ocaml wasm console message by mistake

**Comment by StachuDotNet** [comment]
Integration tests failing, before flipping AOT switch: 
df7c533c32a37caff45dab769def5b57

**Comment by StachuDotNet** [comment]
Relevant note in our code: https://github.com/darklang/dark/blob/main/fsharp-backend/src/Prelude/Prelude.fs#L877-L888

**Comment by StachuDotNet** [comment]
I've been able to run integration tests locally, but I'm still not seeing the issues that CI is seeing.

Checking the CircleCi config, the only substantial differences between how they're run are:
- the tests are split up to be run on separate machines
- only some of the tests are run in CI
- tests are run with a `--published` flag, assuming a publish build.

only that third bullet seems relevant here. To replicate this, I stopped the auto-compile process in VS code, compiled the F# backend manually with the `--optimize` flag, and ran `integration-tests/run.sh` with a `--published` flag. Still, tests pass locally and fail with a bug that looks to be relevant to serialization.

@pbiggar any ideas here? I'm stumped and have been sitting at this issue for a while with no progress.

**Comment by pbiggar** [comment]
> To replicate this, I stopped the auto-compile process in VS code, compiled the F# backend manually with the --optimize flag,

I'm not sure if there'd be a difference, but the correct way to do this is to run `scripts/build/compile-project fsharp-backend --optimize`. Is that what you did?

**Comment by StachuDotNet** [comment]
Yes

**Comment by StachuDotNet** [comment]
integration tests are passing in CI now (pre-AOT - trying AOT now)

**Comment by StachuDotNet** [comment]
Once I flip the AOT flag on, I'm getting some build issues in CI that I'm not getting locally:

```
Failed to compile /home/dark/app/fsharp-backend/Build/obj/Wasm/Release/net6.0/wasm/for-publish/System.Private.CoreLib.dll.bc -> /home/dark/app/fsharp-backend/Build/obj/Wasm/Release/net6.0/wasm/for-publish/System.Private.CoreLib.dll.o

 "/usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.linux-x64/6.0.4/tools/bin/clang++"
 	-target wasm32-unknown-emscripten
 	-DEMSCRIPTEN 
 	-mllvm -combiner-global-alias-analysis=false
 	-mllvm -enable-emscripten-cxx-exceptions
 	-mllvm -enable-emscripten-sjlj
 	-mllvm -disable-lsr
 	-D__EMSCRIPTEN_major__=2
 	-D__EMSCRIPTEN_minor__=0
 	-D__EMSCRIPTEN_tiny__=23
 	-D_LIBCPP_ABI_VERSION=2
 	-Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL
 	--sysroot=/usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.linux-x64/6.0.4/tools/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -O2 -v -c /home/dark/app/fsharp-backend/Build/obj/Wasm/Release/net6.0/wasm/for-publish/System.Private.CoreLib.dll.bc -o /tmp/tmp35xRot.tmp

clang version 13.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 5852582532b3eb3ea8da51a1e272d8d017bd36c9)

Target: wasm32-unknown-emscripten

Thread model: posix

InstalledDir: /usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.linux-x64/6.0.4/tools/bin

 (in-process)

 "/usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.linux-x64/6.0.4/tools/bin/clang++" -cc1 -triple wasm32-unknown-emscripten -emit-obj --mrelax-relocations -disable-free -main-file-name System.Private.CoreLib.dll.bc -mrelocation-model static -mframe-pointer=none -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility hidden -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/dark/app/fsharp-backend/src/Wasm -resource-dir /usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.linux-x64/6.0.4/tools/lib/clang/13.0.0 -O2 -Werror=implicit-function-declaration -fdebug-compilation-dir=/home/dark/app/fsharp-backend/src/Wasm -ferror-limit 19 -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -iwithsysroot/include/SDL -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/tmp35xRot.tmp -x ir /home/dark/app/fsharp-backend/Build/obj/Wasm/Release/net6.0/wasm/for-publish/System.Private.CoreLib.dll.bc

clang -cc1 version 13.0.0 based upon LLVM 13.0.0git default target x86_64-unknown-linux-gnu

emcc: error: '/usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.linux-x64/6.0.4/tools/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=23 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.linux-x64/6.0.4/tools/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -O2 -v -c /home/dark/app/fsharp-backend/Build/obj/Wasm/Release/net6.0/wasm/for-publish/System.Private.CoreLib.dll.bc -o /tmp/tmp35xRot.tmp' failed (received SIGKILL (-9)) [took 94.561s]
```

(this has been slightly edited for reading)

**Comment by StachuDotNet** [comment]
The `wasm32-unknown-emscripten` is looking out of place here, so suspecting that _that_ is the culprit.

**Comment by StachuDotNet** [comment]
While I haven't been able to get AOT running yet on -prod, this PR does accomplish 2 things:
- Wasm.fs is a bit tidier, with more commentary
- we're using _published_ release builds, resulting in less custom stuff in our `compile` script

Once CI is happy, I'll request a review here and leave actual AOT to another PR tomorrow.

**Comment by StachuDotNet** [comment]
- Integration tests run+pass against CI when not AOT'd
- AOT build now works in CI
- integration tests _nearly_ pass in CI against AOT build - I'm down to 2 failing tests, and 1 flaky test

I've had to do some rough things to get integration tests to pass in CI though, namely due to how long it takes Blazor to load. Before this is merged, some of those actions need to be revisited.

**Comment by StachuDotNet** [comment]
Trying two paths now:
- [ ] add lots of console.logs to blazorworker, to pinpoint why blazor seems to not be loading for the failing tests
- [ ] (priority) use the standard blazor.webassembly.js again - maybe it'll work in the background now with its recent updates

Still unsure why we're seeing inconsistent results across local vs. CI - potentially network speed? though that sounds off.

**Comment by StachuDotNet** [comment]
Current status:
The Wasm.fsproj project successfully AOT builds in CI, but integration tests are failing in CI, inconsistently.
The issue seems related to the slow loading of Blazor, but I don't have clarify on the exact issue.
(theories welcome, but I'm not yet blocked. [here](https://app.circleci.com/pipelines/github/darklang/dark/2976/workflows/d1c6137c-f12f-4c39-bc30-ce0cc9f5bece/jobs/32001/tests#failed-test-0)'s a sample CI build with several failures)

[1] It roughly feels as though the integration tests are somehow not well set-up for Blazor loading slowly. There's a measure taken within `integration-tests/tests.ts` to wait for the `Blazor loaded` console message to be seen before continuing with a test. It's used within a few tests - I tried experimenting with this theory by awaiting for that `awaitAnalysisLoad` promise to resolve in the `beforeEach`, but this didn't seem to help. One extension of this would be to 'warm up' the blazor evaluation - I feel like the first eval might take some warm-up time.

So, integration tests are failing, and it's not clear why.

---

Here are some experiments on my list:
- [ ] add many console.logs to reference in CI (either raw or in playwright trace playbacks) to clarify if some race condition is relevant here
  - [ ] in `integration-tests/tests.ts` (especially when the `blazor loaded` promise is resolved)
  - [ ] in BlazorWorker (when loading, when loaded, when evaling)
  - [ ] in appsupport and the client in general (when loaded, when evaling, when the loading spinner starts/ends, etc.)
- [ ] try the official blazor loader within the main thread (without hacks, blocking UI)
- [ ] (if the above works out), make Wasm.fs calls async again, with either of:
  - [ ] re-hack `blazor.webassembly.js` to work in a webworker
  - [ ] load `blazor.webassembly.js` in a hidden iframe, and communicate back/forth with that (is this bad? Wouldn't require the window-smashing that a webworker would)
- [ ] cancel evals when new ones come in (back to your idea, Paul!)
- [ ] try 'warming up' the Blazor eval, out of suspicion that the first eval takes longer than subsequent ones
  - [ ] adjust `awaitAnalysisLoad` to also wait for such a warm-up eval
- [ ] revisit .net7 and `dotnet-wasi-sdk` - maybe the decreased load time that came with that will be worth the upgrade.

**Comment by StachuDotNet** [comment]
Wow, `We've loaded blazor 329185` in the logs shows that it took ~5.5mins for Blazor to load in Playwright in CI.

Other logs:
- `We've created a binding to Wasm.fs 329702`
  .5s after blazor-load. Slower than I'd expect, but reasonable
- `We've made a call to Wasm.fs 342790`
  13s after we create the binding. Pretty surprising.

The wasm "warmth" seems marginal in comparison the Blazor load, but it's still a factor.

Now I'm wondering if Playwright is too restricted by CPU/RAM, networked throttled, etc.
Also, curious about ApiServer and whether it's struggling to keep up with the demand.

**Comment by pbiggar** [comment]
> Set integration test parallelism to 2

Changing parallelism won't affect the server, as it will use fewer/more servers of the same size. Maybe try a larger resource_class?

**Comment by StachuDotNet** [comment]
I'll try that next - this was an experiment to see if stressing apiserver less would help (fewer concurrent requests). Does it seem reasonable towards that goal?

**Comment by StachuDotNet** [comment]
Ah, I see - it isn't.

**Comment by pbiggar** [comment]
Ideas:

- maybe compression isn't working and so it's taking forever to load
- I believe there's some setting in playwright that allows you to load the browser to a certain state, then duplicate that state to later tests. That might help mask whatever we're seeing
- maybe try a new version of playwright? Latest is 1.22, we're on 1.17

**Comment by StachuDotNet** [comment]
wow, a passing build!
https://app.circleci.com/pipelines/github/darklang/dark/2997/workflows/eecf5517-2c9b-4938-9eb3-ad82af0a5b26

Currently the tests are taking at most 1min, with the larger server - I'll set timeout to 90s for now.
This still begs the question of why Blazor's taking so long to load in CI.

**Comment by StachuDotNet** [comment]
This PR was full of many messy commits; I've just squashed them all down into one commit, adding some commentary. If CI passes, I'd recommend we merge this, and I'll extract out a few TODOs, incl. improving CI performance/resource usage.

**Comment by StachuDotNet** [comment]
#3831 replaces this.

**Pull request closed without merging**
